# Source: https://github.com/panubo/reference-github-actions/blob/main/goreleaser-build.yml
# Description: Release a go binary
# LICENSE: MIT License, Copyright (c) 2021-2022 Volt Grid Pty Ltd t/a Panubo

name: GoReleaser Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

env:
  GITHUB_ROLE_ARN: arn:aws:iam::461800378586:role/GitHubECRPublic

permissions:
  id-token: write   # Required for OIDC
  contents: write   # This is required for actions/checkout and creating releases
  actions: write    # Require to upload artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            goreleaser
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            goreleaser --snapshot
          fi

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          path: dist/*
